### ISSUE TITLE
TOML Parse and Rewriting not handling comments and indentation

### ISSUE THREAD

**Issue by lupaulus** [python-poetry/tomlkit#392]
Hello,

Using tomlkit 0.13.2, having a problem when read and rewriting the content.
The comments and the indentation disappear.

```python
        if not bool(self._config):
            return None

        if not os.path.exists(self.path):
            open(self.path, 'a').close()

        # Read content of file
        with open(self.path, 'r', encoding="utf-8") as file:
            # Read the entire content of the file
            content = file.read()

        doc = tomlkit.parse(content)
        doc.update(self._config) # config Dict from

        with open(self.path, 'w', encoding="utf-8") as file:
            file.write(tomlkit.dumps(doc))
```

Config load
```
        with open(self.path, "r") as file:
            self._config = tomlkit.load(file).unwrap()
            return self._config

```

Here the toml as input
```toml
[Publisher]
   [Publisher.Specifications]
       Protocol = "MQTTv5"
       Port = 1166
       SendTimePeriod = 20 # seconds
       TimeGroupPeriod = 200 # milliseconds
#       ProxyHost = "111.111.111.111"
#       ProxyPort = 1616
```

Here the toml as output
```toml
[Publisher.Specifications]
Protocol = "MQTTv5"
Port = 1166
SendTimePeriod = 20
TimeGroupPeriod = 200
```
